global using Microsoft.AspNetCore.Mvc;
global using TvSeriesApi.DTO.Actor;
global using TvSeriesApi.DTO.TvSeries;
global using TvSeriesApi.DTO.Season;
global using TvSeriesApi.DTO.Genre;
global using TvSeriesApi.DTO.Episode;
global using TvSeriesApi.Services.Interfaces;
global using TvSeriesApi.Services;
global using Swashbuckle.AspNetCore.Annotations;